<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Ivaan" failures="6" tests="9" name="Login and Admin Tests" time="138.092" errors="0" timestamp="2025-08-25T21:01:59 IST">
  <testcase classname="tests.LoginTest" name="loginTest" time="4.172"/>
  <testcase classname="tests.AdminSearchTest" name="searchAdminUserTest" time="9.042"/>
  <testcase classname="tests.LoginDataProviderTest" name="loginDDT" time="9.135"/>
  <testcase classname="tests.LoginDataProviderTest" name="loginDDT" time="4.66">
    <failure type="java.lang.AssertionError" message="Login failed.">
      <![CDATA[java.lang.AssertionError: Login failed.
at tests.LoginDataProviderTest.loginDDT(LoginDataProviderTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="tests.LoginDataProviderTest" name="loginDDT" time="4.596">
    <failure type="java.lang.AssertionError" message="Login failed unexpectedly — no dashboard and no error message.">
      <![CDATA[java.lang.AssertionError: Login failed unexpectedly — no dashboard and no error message.
at tests.LoginDataProviderTest.loginDDT(LoginDataProviderTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="tests.LoginDataProviderTest" name="loginDDT" time="4.152">
    <failure type="java.lang.AssertionError" message="Login failed unexpectedly — no dashboard and no error message.">
      <![CDATA[java.lang.AssertionError: Login failed unexpectedly — no dashboard and no error message.
at tests.LoginDataProviderTest.loginDDT(LoginDataProviderTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="tests.LoginDataProviderTest" name="loginDDT" time="4.182">
    <failure type="java.lang.AssertionError" message="Login failed unexpectedly — no dashboard and no error message.">
      <![CDATA[java.lang.AssertionError: Login failed unexpectedly — no dashboard and no error message.
at tests.LoginDataProviderTest.loginDDT(LoginDataProviderTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="tests.LoginDataProviderTest" name="loginDDT" time="3.542">
    <failure type="java.lang.AssertionError" message="Login failed unexpectedly — no dashboard and no error message.">
      <![CDATA[java.lang.AssertionError: Login failed unexpectedly — no dashboard and no error message.
at tests.LoginDataProviderTest.loginDDT(LoginDataProviderTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="tests.LoginDataProviderTest" name="loginDDT" time="3.545">
    <failure type="java.lang.AssertionError" message="Login failed unexpectedly — no dashboard and no error message.">
      <![CDATA[java.lang.AssertionError: Login failed unexpectedly — no dashboard and no error message.
at tests.LoginDataProviderTest.loginDDT(LoginDataProviderTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="base.BaseTest" name="@BeforeSuite cleanScreenshotsOnce" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite cleanScreenshotsOnce -->
  <testcase classname="base.BaseTest" name="@BeforeSuite cleanScreenshotsOnce" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite cleanScreenshotsOnce -->
</testsuite> <!-- Login and Admin Tests -->
